version: "3.8"

services:
  service-one:
    image: my-node-app:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: any

  service-two:
    image: my-node-app:latest
    ports:
      - "3001:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
